### ISSUE TITLE
Misc Todo

### ISSUE THREAD

**Issue by TakosThings** [TakosThings/Fluent-Discord#287]
- [x] Voice UI volume control
- [x] Voice connected guild indicator icon alignment within circle
- [x] User settings: Privacy and safety pivot
- [x] User settings: Sidebar scrolbar thumb
- [x] User settings: BD version info text colour
- [x] Check top and left border width around chat area
